export {
  IMAGE_PROXY_MAX_CONCURRENT_PER_USER,
  IMAGE_PROXY_MAX_RESPONSE_BYTES,
  IMAGE_PROXY_RATE_LIMIT_MAX,
  IMAGE_PROXY_RATE_LIMIT_WINDOW_MS,
  IMAGE_PROXY_REDIS_SLOT_TTL_SEC,
  IMAGE_PROXY_UPSTREAM_TIMEOUT_MS,
} from "@/lib/rate-limit/api-quotas";
